// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmdnvnzfdbezwuyovfdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZG52bnpmZGJlend1eW92ZmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NzYwODQsImV4cCI6MjA3NzI1MjA4NH0.l2Ex7-MDLjaR5ZpI1D1MZ_r5sfm4gkCTUh5ROTY5E34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});